##' Estimate effects for a set of mediation markers
##' V2 this version allow to integrate covariates in mediation function 
##'
##' Estimate various quantities for causal mediation analysis for a set of
##' markers, including average causal mediation effects
##' (indirect effect), average direct effects, proportions mediated,
##' and total effect.
##'
##' @param object results from hdmax2 step 2
##' @param m a response variable matrix with n rows and p columns corresponding to mediators selected at step1.
##' Response variables must be encoded as numeric. No NAs allowed.
##' @param sims number of Monte Carlo draws for nonparametric bootstrap or quasi-Bayesian approximation.
##' 10000 is recommended.
##' @param boots number of bootstrap
##' @param multivariate choose if for categorial exposure categories treated a single variate or compute in partiel regression (full=TRUE)
##'
##'
##' @return hdmax2_step2 object
##' 
##'  - ACME, estimation of the average causal mediation effect (the indirect effect)
##'  - ADE, estimation average direct effect
##'  - PM, estimation of the proportion mediated
##'  - TE, estimation of the total effect
##'  
##' Regressions:
##'  - xm, regression X on M
##'  - my, regression M on Y
##' 
##' 
##' Overall effect
##'  - oie, overall indirect effect
##'  - oie_med , oie median
##'  - oie_sd , oie standard deviation
##'  - ote, overall total effect
##'  - ode, overall direct effect
##'  
##' @details
##'
##' We use the mediate function of the mediation package on the set of markers having Q-value lower
##' than the FDR threshold. It estimates their indirect effects and 
##' tests their significance.
##'
##' @export
##' @author Florence Pittion
##' @examples 
##' data(simu_data)
##' res_step1 = run_AS(X_matrix = simu_data$X_binary ,
##' Y_matrix = simu_data$Y_continuous,
##' M_matrix = simu_data$M, 
##' K = 5,
##' X_type = "binary",
##' Y_type = "continuous",
##' M_type = "methylation",
##' multivariate = FALSE,
##' covar = cbind(simu_data$age, simu_data$gender),
##' diagnostic.plot = F)
##' 
##' mediators_top10 = simu_data$M[,names(sort(res_step1$max2)[1:10])]
##' res_step2 = estimate_effect(object = res_step1,
##' m = mediators_top10,
##' boots = 100,
##' sims = 100)

estimate_effect_V2 <- function(object , m, boots = 100, sims = 3, multivariate = FALSE) {
  
  if (class(object)!="hdmax2_step1"){
    stop("The object is not of class hdmax2_step1. This function only compute hdmax2 objects generated by hdmax2::run_AS")
  }
  
  if (is.null(colnames(m))) {
    colnames(m) <- 1:ncol(m)
  }
  
  M = m
  #mediators_top10 = M[,names(sort(res_step1$max2_pvalues[1,]))[1:10]]
  
  ### variables definition
  if(!object$input$multivariate) {
    X = as.matrix(object$input$X_matrix)
  }
  if (object$input$multivariate) {
    n = dim(object$input$X_matrix)[2]
    X = as.matrix(object$input$X_matrix[,1])
    X_otherCats = as.data.frame(object$input$X_matrix[,-1])
    X_otherCats = X_otherCats[,-(n-2)]
  }
  # if (multivariate) {
  #   n = dim(object$input$X_matrix)[2]
  #   Xs = list()
  #   Xs_otherCats = list()
  #   for(i in (1:n)){
  #   ## seule option pour le moment est de prendre la premiere categorie , voir comment le faire pour toutes les categorie 
  #   X = as.matrix(object$input$X_matrix[,i])
  #   X_otherCats = as.data.frame(object$input$X_matrix[,-i])
  #   ## -1 colonne (la derriere c'est arbitraire) POUR EVITER LA COLINEARITE
  #   X_otherCats = X_otherCats[,-(n-2)]
  #   
  #   Xs[[i]] =X 
  #   Xs_otherCats[[i]] = X_otherCats 
  #   }
  # }
  Y = object$input$Y_matrix
  X_type = object$input$X_type
  Y_type = object$input$Y_type
  
  
  
  ### total covariable (covars composition)
  if (!object$input$multivariate) {
    if (is.null(object$input$covar)) {
      covars = data.frame(latent_factors = object$modele_1$U)
    } else  {
      covars = data.frame(obs_covar = object$input$covar, latent_factors = object$modele_1$U)
    }
  }
  if (object$input$multivariate) {
    if (is.null(object$input$covar)) {
      covars = data.frame(latent_factors = object$modele_1$U, X_otherCats = X_otherCats)
    } else  {
      covars = data.frame(obs_covar = object$input$covar, latent_factors = object$modele_1$U, X_otherCats = X_otherCats)
    }
  }
  
  
    ### Compute ACME, ADE, PM and TE from package mediation
    
    # from package mediation
    ACME <- matrix(ncol = 4, nrow = ncol(M))
    ADE <- matrix(ncol = 4, nrow = ncol(M))
    PM <- matrix(ncol = 4, nrow = ncol(M))
    TE <- matrix(ncol = 4, nrow = ncol(M))
    
    # from linear models
    xm <- matrix(ncol = 4, nrow = ncol(M))
    my <- matrix(ncol = 4, nrow = ncol(M))
    
    ###############################
    # covars are considered in mediate function but not in input regression modele
    ###############################
    
    
    
    for (i in 1:ncol(M)) {
      
      if (!multivariate) {
        if (is.null(object$input$covar)) {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U)
        } else  {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar)
        }
      }
      if (multivariate) {
        if (is.null(object$input$covar)) {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U,  X_otherCats = X_otherCats)
        } else  {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, X_otherCats =X_otherCats)
        }
      }
      
      if (!multivariate) {
        if (is.null(object$input$covar)) {
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, Y = Y)
        } else  {
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, Y = Y)
        }
      }
      if (multivariate) {
        if (is.null(object$input$covar)) {
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U,  X_otherCats = X_otherCats, Y = Y)
        } else  {
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, X_otherCats =X_otherCats, Y = Y)
        }
      }
      # dat.x <- data.frame(X = X, Mi = M[, i], covars = covars)
      # dat.y <- data.frame(X = X, Mi = M[, i], Y = Y, covars = covars)
      
      # ici cas de deux reg lineaires pour les deux associations
      # TODO refaire pour les autres regressions
      
      
      mod1 <- stats::lm(Mi ~ X + ., data = dat.x)
      
      if(Y_type=="continuous"){
        mod2 <- stats::lm(Y ~ X + Mi + ., data = dat.y)
      }
      
      if(Y_type=="binary"){
        mod2 <- stats::glm(Y ~ X + Mi + ., data = dat.y)
      }
      
      # if(mod2_type=="surv_Cox"){
      # mod2 = survival::survreg(Y ~ X + Mi , dist='exponential', data = dat.y)
      # }
      
      
      # for linear models
      xm[i, ] <- summary(mod1)$coeff[2, ] # effect of X
      #if(Y_type=="binary"){
      my[i, ] <- summary(mod2)$coeff[3, ] # effect of M
      #}
      
      
      med <- mediation::mediate(mod1, mod2, sims = sims, treat = "X", mediator = "Mi", covariates = dat.x[,3:dim(dat.x)[2]])
      
      ACME[i, ] <- c(med$d0, med$d0.ci[1], med$d0.ci[2], med$d0.p)
      ADE[i, ] <- c(med$z0, med$z0.ci[1], med$z0.ci[2], med$z0.p)
      PM[i, ] <- c(med$n0, med$n0.ci[1], med$n0.ci[2], med$n0.p)
      TE[i, ] <- c(med$tau.coef, med$tau.ci[1], med$tau.ci[2], med$tau.p)
    }
    
    ACME <- as.data.frame(ACME)
    ADE <- as.data.frame(ADE)
    PM <- as.data.frame(PM)
    TE <- as.data.frame(TE)
    xm <- as.data.frame(xm)
    my <- as.data.frame(my)
    
    colnames(ACME) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(ADE) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(PM) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(TE) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(xm) <- c("Estimate", "Std.Error", "t.Value", "pValue")
    colnames(my) <- c("Estimate", "Std.Error", "t.Value", "pValue")
    
    ACME$feat <- colnames(M)
    ADE$feat <- colnames(M)
    PM$feat <- colnames(M)
    TE$feat <- colnames(M)
    xm$feat <- colnames(M)
    my$feat <- colnames(M)
    
    ### Compute OIE by bootstrap
    
    # bootstrap
    acme_sum <- matrix(nrow = 1, ncol = boots)
    covars = as.matrix(covars)
    
    for (i in 1:ncol(acme_sum)) {
      samp <- sample(length(X), replace = T)
      
      
      # effet A X -> M
      mod1 <- lm(m[samp, ] ~ X[samp] + covars[samp, ])
      A <- t(sapply(summary(mod1), function(x) x$coeff[2, ]))
      A <- data.frame(feat = rownames(A), A)
      # A <- separate(A, CpG, c("0", "CpG"), " ")[, -1]
      
      
      # effet B m -> Y
      if(Y_type=="binary"){
        dat.1 <- data.frame(X, m, covars = covars)
        mod2 <- glm(Y[samp] ~ ., data = dat.1[samp, ])
        B <- as.data.frame(summary(mod2)$coeff[3:(ncol(m) + 2), ])
      } 
      
      if(Y_type=="continuous"){
        dat.1 <- data.frame(X, m, covars = covars)
        mod2 <- lm(Y[samp] ~ ., data = dat.1[samp, ])
        B <- as.data.frame(summary(mod2)$coeff[3:(ncol(m) + 2), ])
        #B <- as.data.frame(summary(mod2)$coeff[3:10, ])
      }
      
      
      colnames(B) <- c("B", "B_sd", "B_tv", "B_pv")
      colnames(A)[2:5] <- c("A", "A_sd", "A_tv", "A_pv")
      
      ab <- cbind(A, B)
      rownames(ab) <- NULL
      
      # effet A*B
      ab$AB <- ab$A * ab$B
      
      acme_sum[i] <- sum(ab$AB)
    }
    
    ### Compute ODE and OTE for the given model
    if(Y_type == "continuous") {
      mod_total_effect = lm(Y ~ X + covars)
      ote = mod_total_effect$coefficients
      
      mod_direct_effect = lm(Y ~ X + mediators_top10 + covars)
      ode = mod_direct_effect$coefficients
    }
    
    if(Y_type == "binary") {
      mod_total_effect = glm(Y ~ X + covars)
      ote = mod_total_effect$coefficients
      
      mod_direct_effect = glm(Y ~ X + mediators_top10 + covars)
      ode = mod_direct_effect$coefficients
    }
    
    obj = list(ACME = ACME,
               ADE = ADE,
               PM = PM,
               TE = TE,
               xm = xm,
               my = my,
               oie = as.vector(acme_sum),
               oie_med = median(as.vector(acme_sum)),
               oie_sd = sd(as.vector(acme_sum)),
               ote = ote,
               ode = ode
    )
    
    class(obj) = "hdmax2_step2"
    
    return(obj)
    
  }
  