##' Summary plot for HDMAX2
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_continuous ,
##'   Y =  simu_data$Y_continuous,
##'   M =  simu_data$M
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(
##'    object = hdmax2_step1, 
##'    m = mediators_top10)
##' hdmax2::plot_hdmax2(hdmax2_step2)
##' @import ggplot2
##' @importFrom stats reshape

plot_hdmax2 <- function(object) {
  
  if (class(object)!="hdmax2_step2"){
    stop("The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect")
  }
  
  #Plot the ACME of the model
  if(length(object$input$expo_var_ids) == 1 & (object$input$expo_var_types!="character")) {
    print("hdmax2 plot for univariate exposome")
    p = plot_univariate(object)
  }
  
  if(length(object$input$expo_var_ids) == 1 & (object$input$expo_var_types=="character")) {
    print("hdmax2 plot for univariate categorial exposome")
    p = plot_univariate_cat(object)
  }
  
  
  if (length(object$input$expo_var_ids) > 1 ) {
    print("hdmax2 plot for multivariate exposome")
    p = plot_multivariate(object)
  }
  
  return(p)  
}  


##' Summary plot for univariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_continuous ,
##'   Y =  simu_data$Y_continuous,
##'   M =  simu_data$M
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(
##'    object = hdmax2_step1, 
##'    m = mediators_top10)
##' hdmax2::plot_univariate(hdmax2_step2)
##' @import ggplot2
##' @importFrom stats reshape

plot_univariate <- function(object) {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }
  
  
  # Plot the ACME of the model
  
  p_ACME <-
    ggplot2::ggplot(
      object$ACME[[1]],
      aes(
        object$ACME[[1]]$est,
        object$ACME[[1]]$feat,
        #stats::reorder(object$ACME$feat, object$ACME$est),
        color = est <= 0,
        shape = pval <= 0.05
      )
    ) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_errorbarh(aes(xmin = object$ACME[[1]]$CI_2.5, xmax = object$ACME[[1]]$CI_97.5)) +
    geom_point(size = 2.8) +
    theme_bw() +
    labs(title = "A. ACME (Average Causal Mediation Effect)", y = "Mediators", x =
           "Est. effect [CI 2.5-97.5]") +
    #xlab("ACME (Average Causal Mediation Effect)") +
    #ylab("CpG") +
    theme(
      panel.border = element_blank(),
      panel.spacing = unit(0.01, "lines"),
      axis.ticks = element_blank()
    ) +
    scale_color_manual(values = c("darkred", "darkgreen"))
  
  
  ## Plot the mediated proportion
  
  p_PM <-
    ggplot2::ggplot(object$PM[[1]],
                    aes(
                      object$PM[[1]]$est,
                      object$ACME[[1]]$feat,
                      #stats::reorder(object$PM$feat, object$PM$est),
                      color = est <= 0,
                      shape = pval <= 0.05
                    )) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_errorbarh(aes(xmin = object$PM[[1]]$CI_2.5, xmax = object$PM[[1]]$CI_97.5)) +
    geom_point(size = 2.8) +
    theme_bw() +
    labs(title = "B. Proportion Mediated (%)", y = "Mediators", x = "Est. proportion [CI 2.5-97.5]") +
    # xlab("Proportion Mediated (%)") +
    #ylab("CpG") +
    theme(
      panel.border = element_blank(),
      panel.spacing = unit(0.01, "lines"),
      axis.ticks = element_blank()
    ) +
    scale_color_manual(values = c("darkred", "darkgreen"))
  
  ## Plot the overall effects
  
  df_effect = data.frame(OIE = object$oie_med[[1]], # median of OIE
                         OIE_CI = object$oie_sd[[1]], # confidence interval computed by boostrap
                         ODE =  object$ode[[1]][1], # coefficient of direct effect linear regression
                         ODE_sd =  object$ode[[1]][2], # sd of direct effect linear regression
                         OTE =  object$ote[[1]][1], # coefficient of total effect linear regression
                         OTE_sd =  object$ote[[1]][2]) # sd of total effect linear regression
  df_effect_long <-
    reshape(
      df_effect,
      varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
      v.names = c("value", "sd_value"),
      timevar = "variable",
      times = c("OIE", "ODE", "OTE"),
      direction = "long"
    )
  
  p_effects <-
    ggplot2::ggplot(df_effect_long, aes(
      x = df_effect_long$variable,
      y = df_effect_long$value,
      group = 1
    )) +
    geom_line() +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) + 
    geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
    labs(title = "C. Overall effect",
         x = NULL,
         y = "Effect size") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
      panel.grid.minor = element_blank(),
    )
  
  
  ## Plot the effect size
  
  df = data.frame(
    mediator = object$xm[[1]]$feat,
    step1 = object$xm[[1]]$Estimate,
    step2 = object$my[[1]]$Estimate,
    ACME = object$ACME[[1]]$est
  )
  df = dplyr::arrange(df, dplyr::desc(df$ACME))
  #df$mediator <- factor(df$mediator, levels = df$mediator)
  
  df_long <- data.frame(
    mediator = rep(df$mediator, 3),
    variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
    value = c(df$step1, df$step2, df$ACME)
  )
  
  p_es = ggplot2::ggplot(df_long, aes(
    x = factor(mediator),
    y = value,
    fill = variable
  )) +
    geom_bar(
      data = subset(df_long, variable == "ACME"),
      stat = "identity",
      position = position_dodge(width = 0.7),
      size = 1.5
    )  +
    geom_bar(
      data = subset(df_long, variable != "ACME"),
      stat = "identity",
      position = position_dodge(width = 0.7),
      size = 0.2,
      alpha = 0.3
    )  +
    
    
    labs(title = "D. Indirect effect sizes for selected mediators", x = "Mediator", y = "Mediated effect") +
    scale_fill_manual(
      values = c(
        "step1" = "purple",
        "step2" = "cyan",
        "ACME" = "black"
      ),
      name = "Ind. Effect :",
      labels = c(
        "step1" = "Effect of X on M", # a from "M ~ X"
        "step2" = "Effect of M on Y", # b from "Y ~ X + M"
        "ACME" = "ACME" # axb
      )
    ) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top" )
  
  
  plot_final = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)

  return(plot_final)
}





##' Summary plot for univariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_continuous ,
##'   Y =  simu_data$Y_continuous,
##'   M =  simu_data$M
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(
##'    object = hdmax2_step1, 
##'    m = mediators_top10)
##' hdmax2::plot_univariate(hdmax2_step2)
##' @import ggplot2
##' @importFrom stats reshape

plot_univariate_cat <- function(object) {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }
 n_cat = length(unique(object$input$X_input))-1
 plot_final = list()
 
  # Plot the ACME of the model
  for(k in 1:n_cat){
    p_ACME <-
      ggplot2::ggplot(
        object$ACME[[1]][[k]],
        aes(
          object$ACME[[1]][[k]]$est,
          object$ACME[[1]][[k]]$feat,
          #stats::reorder(object$ACME[[1]][[k]]$feat, object$ACME[[1]][[k]]$est),
          color = object$ACME[[1]][[k]]$est <= 0,
          shape = object$ACME[[1]][[k]]$pval <= 0.05
        )
      ) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$ACME[[1]][[k]]$CI_2.5, xmax = object$ACME[[1]][[k]]$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = "A. ACME (Average Causal Mediation Effect)", y = "Mediators", x =
             "Est. effect [CI 2.5-97.5]") +
      #xlab("ACME (Average Causal Mediation Effect)") +
      #ylab("CpG") +
      theme(
        panel.border = element_blank(),
        panel.spacing = unit(0.01, "lines"),
        axis.ticks = element_blank()
      ) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    
    ## Plot the mediated proportion
    
    p_PM <-
      ggplot2::ggplot(object$PM[[1]][[k]],
                      aes(
                        object$PM[[1]][[k]]$est,
                        object$ACME[[1]][[k]]$feat,
                        #stats::reorder(object$PM[[1]][[k]]$feat, object$PM[[1]][[k]]$est),
                        color = object$PM[[1]][[k]]$est <= 0,
                        shape = object$PM[[1]][[k]]$pval <= 0.05
                      )) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$PM[[1]][[k]]$CI_2.5, xmax = object$PM[[1]][[k]]$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = "B. Proportion Mediated (%)", y = "Mediators", x = "Est. proportion [CI 2.5-97.5]") +
      # xlab("Proportion Mediated (%)") +
      #ylab("CpG") +
      theme(
        panel.border = element_blank(),
        panel.spacing = unit(0.01, "lines"),
        axis.ticks = element_blank()
      ) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    ## Plot the overall effects
    
    # df_effect = data.frame(OIE = object$oie_med[[1]][[k]], # median of OIE
    #                        OIE_CI = object$oie_sd[[1]][[k]], # confidence interval computed by boostrap
    #                        ODE =  object$ode[1], # coefficient of direct effect linear regression
    #                        ODE_sd =  object$ode[2], # sd of direct effect linear regression
    #                        OTE =  object$ote[1], # coefficient of total effect linear regression
    #                        OTE_sd =  object$ote[2]) # sd of total effect linear regression
    # df_effect_long <-
    #   reshape(
    #     df_effect,
    #     varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
    #     v.names = c("value", "sd_value"),
    #     timevar = "variable",
    #     times = c("OIE", "ODE", "OTE"),
    #     direction = "long"
    #   )
    # 
    # p_effects <-
    #   ggplot2::ggplot(df_effect_long, aes(
    #     x = df_effect_long$variable,
    #     y = df_effect_long$value,
    #     group = 1
    #   )) +
    #   geom_line() +
    #   geom_point(size = 3) +
    #   geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) + 
    #   geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
    #   labs(title = "C. Overall effect",
    #        x = NULL,
    #        y = "Effect size") +
    #   theme_minimal() +
    #   theme(
    #     axis.text.x = element_text(angle = 45, hjust = 1),
    #     panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
    #     panel.grid.minor = element_blank(),
    #   )
    
    
    ## Plot the effect size
    
    df = data.frame(
      mediator = object$xm[[1]][[k]]$feat,
      step1 = object$xm[[1]][[k]]$Estimate,
      step2 = object$my[[1]][[k]]$Estimate,
      ACME = object$ACME[[1]][[k]]$est
    )
    df = dplyr::arrange(df, dplyr::desc(df$ACME))
    #df$mediator <- factor(df$mediator, levels = df$mediator)
    
    df_long <- data.frame(
      mediator = rep(df$mediator, 3),
      variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
      value = c(df$step1, df$step2, df$ACME)
    )
    
    p_es = ggplot2::ggplot(df_long, aes(
      x = factor(mediator),
      y = value,
      fill = variable
    )) +
      geom_bar(
        data = subset(df_long, variable == "ACME"),
        stat = "identity",
        position = position_dodge(width = 0.7),
        linewidth = 1.5
      )  +
      geom_bar(
        data = subset(df_long, variable != "ACME"),
        stat = "identity",
        position = position_dodge(width = 0.7),
        linewidth = 0.2,
        alpha = 0.3
      )  +
      
      
      labs(title = "D. Indirect effect sizes for selected mediators", x = "Mediator", y = "Mediated effect") +
      scale_fill_manual(
        values = c(
          "step1" = "purple",
          "step2" = "cyan",
          "ACME" = "black"
        ),
        name = "Ind. Effect :",
        labels = c(
          "step1" = "Effect of X on M", # a from "M ~ X"
          "step2" = "Effect of M on Y", # b from "Y ~ X + M"
          "ACME" = "ACME" # axb
        )
      ) + 
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top" )
    
    plot_final[[k]] = gridExtra::grid.arrange(p_ACME, p_PM,  p_es, ncol = 2) # p_effects,
    #plot_final = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
   
  }
  return(plot_final)
}





##' Summary plot for multivariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' X_matrix = simu_data$X_categorial
##' Y_matrix = simu_data$Y_continuous
##'  M_matrix = simu_data$M
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = X_matrix ,
##'   Y =  Y_matrix,
##'   M =  M_matrix
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(
##'    object = hdmax2_step1, 
##'    m = mediators_top10)
##' hdmax2::plot_multivariate(hdmax2_step2)
##' @import ggplot2
##' @importFrom stats reshape
##' 
##' 

plot_multivariate <- function(object) {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }
  
  var_names = colnames(object$input$X_input)
  plot_final = list()
  
  for(var_name in var_names){
    
    p_ACME <- ggplot2::ggplot(object$ACME[[var_name]], aes(object$ACME[[var_name]]$est, stats::reorder(object$ACME[[var_name]]$feat, object$ACME[[var_name]]$est), color = est <= 0, shape = pval <= 0.05)) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$ACME[[var_name]]$CI_2.5, xmax = object$ACME[[var_name]]$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = paste0("A. ACME of ", var_name), y = "Mediators", x="Est. effect [CI 2.5-97.5]") +
      #xlab("ACME (Average Causal Mediation Effect)") +
      #ylab("CpG") +
      theme(panel.border = element_blank(),
            panel.spacing = unit(0.01, "lines"),
            axis.ticks = element_blank()) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    
    ##Plot the mediated proportion
    
    p_PM <- ggplot2::ggplot(object$PM[[var_name]], aes(object$PM[[var_name]]$est, stats::reorder(object$PM[[var_name]]$feat, object$PM[[var_name]]$est), color = est <= 0, shape = pval <= 0.05)) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$PM[[var_name]]$CI_2.5, xmax = object$PM[[var_name]]$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = paste0("B. PM of ", var_name), y = "Mediators", x="Est. proportion [CI 2.5-97.5]") +
      # xlab("Proportion Mediated (%)") +
      #ylab("CpG") +
      theme(panel.border = element_blank(),
            panel.spacing = unit(0.01, "lines"),
            axis.ticks = element_blank()) +
      scale_color_manual(values = c("darkred", "darkgreen")) 
    
    ##Plot the overall effects
    
    df_effect = data.frame(OIE = object$oie_med[[var_name]], # median of OIE
                           OIE_CI = object$oie_sd[[var_name]], # confidence interval computed by boostrap
                           ODE =  object$ode[[var_name]][1], # coefficient of direct effect linear regression
                           ODE_sd =  object$ode[[var_name]][2], # sd of direct effect linear regression
                           OTE =  object$ote[[var_name]][1], # coefficient of total effect linear regression
                           OTE_sd =  object$ote[[var_name]][2]) # sd of total effect linear regression
    df_effect_long <-
      reshape(
        df_effect,
        varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
        v.names = c("value", "sd_value"),
        timevar = "variable",
        times = c("OIE", "ODE", "OTE"),
        direction = "long"
      )
    
    p_effects <- ggplot2::ggplot(df_effect_long, aes(x = df_effect_long$variable, y = df_effect_long$value, group = 1)) +
      geom_line() +
      geom_point(size = 3) +
      geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) + 
      geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
      labs(title = paste0("C. Overall effect of ", var_name),
           x = NULL,
           y = "Effect size") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            #axis.title.y = element_blank(),
            panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
            panel.grid.minor = element_blank(),
            #plot.title = element_text(hjust = 0.5)
      )
    
    ##Plot the effect size
    
    df = data.frame( mediator = object$xm[[var_name]]$feat,
                     step1 = object$xm[[var_name]]$Estimate,
                     step2 = object$my[[var_name]]$Estimate,
                     ACME = object$ACME[[var_name]]$est)
    df = dplyr::arrange(df, dplyr::desc(df$ACME))
    df$mediator <- factor(df$mediator, levels = df$mediator)
    
    df_long <- data.frame(
      mediator = rep(df$mediator, 3),
      variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
      value = c(df$step1, df$step2, df$ACME)
    )
    
    p_es = ggplot2::ggplot(df_long, aes(x = factor(mediator), y = value, fill = variable)) +
      geom_bar(data = subset(df_long, variable == "ACME"), stat="identity", position=position_dodge(width = 0.7), linewidth = 1.5)  +
      geom_bar(data = subset(df_long, variable != "ACME"), stat="identity", position=position_dodge(width = 0.7), linewidth = 0.2,  alpha = 0.3)  +
      
      #geom_text(aes(label = round(value, 2)), position=position_dodge(width = 0.7), vjust = -0.5) +  # Ajouter les étiquettes de taille d'effet
      labs(title = paste0("D. Effect sizes of ", var_name), x = "Mediator", y = "Mediated effect") +
      scale_fill_manual(values = c("step1" = "purple", "step2" = "cyan", "ACME" = "black"),
                        name = "Effects",
                        labels = c(
                          "step1" = "Effect of X on M", # a from "M ~ X"
                          "step2" = "Effect of M on Y", # b from "Y ~ X + M"
                          "ACME" = "ACME" # axb
                        )) +  # Personnalisation de la légende
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))# +
    # guides(fill = guide_legend(override.aes = list(size = c(0.5, 0.5, NA))))  # Ne pas afficher l'épaisseur pour ACME dans la légende
    
    
    #patchwork::combined_plot <- (p_ACME + p_PM) / (p_effects + p_es)
    
    plot_final[[var_name]] = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
    
  }
  return(plot_final)
}

