##' Summary plot for HDMAX2
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @param plot_type  "all_plot" by default generate all proposed plots , elsewhere choose one individual plot among : "plot_ACME", "plot_Prop_Med", "plot_overall_effects", "plot_effect_size"
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' K = 5
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_continuous ,
##'   Y =  simu_data$Y_continuous,
##'   M =  simu_data$M,
##'   K = K
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(object = hdmax2_step1, 
##'                                        m = mediators_top10)
##' # Generate plot
##' hdmax2::plot_hdmax2(hdmax2_step2, plot_type = "all_plot")
##' 
##' @import ggplot2
##' @importFrom stats reshape

plot_hdmax2 <- function(object,  plot_type = "all_plot") {
  
  if (class(object)!="hdmax2_step2"){
    stop("The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect")
  }
  
  #Plot the ACME of the model
  if(length(object$input$expo_var_ids) == 1 &&  is.factor(object$input$X_input)==FALSE && (object$input$expo_var_types!="character")) {
    print("hdmax2 plot for univariate exposome")
    p = plot_univariate(object, plot_type = "all_plot")
  }
  
  if(length(object$input$expo_var_ids) == 1 && (object$input$expo_var_types=="character" || is.factor(object$input$X_input))) {
    print("hdmax2 plot for univariate categorial exposome")
    p = plot_univariate_cat(object, plot_type = "all_plot")
  }
  
  if (length(object$input$expo_var_ids) > 1 ) {
    print("hdmax2 plot for multivariate exposome")
    p = plot_multivariate(object, plot_type = "all_plot")
  }
  
  return(p)  
}  


##' Summary plot for univariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @param plot_type  "all_plot" by default generate all proposed plots , elsewhere choose one individual plot among : "plot_ACME", "plot_Prop_Med", "plot_overall_effects", "plot_effect_size"
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' K = 5
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_continuous,
##'   Y = simu_data$Y_continuous,
##'   M = simu_data$M,
##'   K = K
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(object = hdmax2_step1, 
##'                                        m = mediators_top10)
##' # Generate plot
##' hdmax2::plot_univariate(hdmax2_step2,  plot_type= "all_plot")
##' 
##' @import ggplot2
##' @importFrom stats reshape

plot_univariate <- function(object,  plot_type= "all_plot") {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }

  
  
  # Plot the ACME of the model
  
  p_ACME <-
    ggplot2::ggplot(
      object$effects[[1]]$ACME,
      aes(
        object$effects[[1]]$ACME$est,
        object$effects[[1]]$ACME$feat,
        #stats::reorder(object$ACME$feat, object$ACME$est),
        color = est <= 0,
        shape = pval <= 0.05
      )
    ) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_errorbarh(aes(xmin = object$effects[[1]]$ACME$CI_2.5, xmax = object$effects[[1]]$ACME$CI_97.5)) +
    geom_point(size = 2.8) +
    theme_bw() +
    labs(title = "A. ACME (Average Causal Mediation Effect)", y = "Mediators", x =
           "Est. effect [CI 2.5-97.5]") +
    #xlab("ACME (Average Causal Mediation Effect)") +
    #ylab("CpG") +
    theme(
      panel.border = element_blank(),
      panel.spacing = unit(0.01, "lines"),
      axis.ticks = element_blank()
    ) +
    scale_color_manual(values = c("darkred", "darkgreen"))
  
  
  ## Plot the mediated proportion
  
  p_PM <-
    ggplot2::ggplot(object$effects[[1]]$PM,
                    aes(
                      object$effects[[1]]$PM$est,
                      object$effects[[1]]$ACME$feat,
                      #stats::reorder(object$PM$feat, object$PM$est),
                      color = est <= 0,
                      shape = pval <= 0.05
                    )) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_errorbarh(aes(xmin = object$effects[[1]]$PM$CI_2.5, xmax = object$effects[[1]]$PM$CI_97.5)) +
    geom_point(size = 2.8) +
    theme_bw() +
    labs(title = "B. Proportion Mediated (%)", y = "Mediators", x = "Est. proportion [CI 2.5-97.5]") +
    # xlab("Proportion Mediated (%)") +
    #ylab("CpG") +
    theme(
      panel.border = element_blank(),
      panel.spacing = unit(0.01, "lines"),
      axis.ticks = element_blank()
    ) +
    scale_color_manual(values = c("darkred", "darkgreen"))
  
  ## Plot the overall effects
  
  df_effect = data.frame(OIE = object$effects[[1]]$oie_med, # median of OIE
                         OIE_CI = object$effects[[1]]$oie_sd, # confidence interval computed by boostrap
                         ODE =  object$effects[[1]]$ode[1], # coefficient of direct effect linear regression
                         ODE_sd =  object$effects[[1]]$ode[2], # sd of direct effect linear regression
                         OTE =  object$effects[[1]]$ote[1], # coefficient of total effect linear regression
                         OTE_sd =  object$effects[[1]]$ote[2]) # sd of total effect linear regression
  df_effect_long <-
    reshape(
      df_effect,
      varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
      v.names = c("value", "sd_value"),
      timevar = "variable",
      times = c("OIE", "ODE", "OTE"),
      direction = "long"
    )
  
  p_effects <-
    ggplot2::ggplot(df_effect_long, aes(
      x = df_effect_long$variable,
      y = df_effect_long$value,
      group = 1
    )) +
    geom_line() +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) + 
    geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
    labs(title = "C. Overall effect",
         x = NULL,
         y = "Effect size") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
      panel.grid.minor = element_blank(),
    )
  
  
  ## Plot the effect size
  
  df = data.frame(
    mediator = object$effects[[1]]$xm$feat,
    step1 = object$effects[[1]]$xm$Estimate,
    step2 = object$effects[[1]]$my$Estimate,
    ACME = object$effects[[1]]$ACME$est
  )
  df = dplyr::arrange(df, dplyr::desc(df$ACME))
  #df$mediator <- factor(df$mediator, levels = df$mediator)
  
  df_long <- data.frame(
    mediator = rep(df$mediator, 3),
    variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
    value = c(df$step1, df$step2, df$ACME)
  )
  
  p_es = ggplot2::ggplot(df_long, aes(
    x = factor(mediator),
    y = value,
    fill = variable
  )) +
    geom_bar(
      data = subset(df_long, variable == "ACME"),
      stat = "identity",
      position = position_dodge(width = 0.7),
      size = 1.5
    )  +
    geom_bar(
      data = subset(df_long, variable != "ACME"),
      stat = "identity",
      position = position_dodge(width = 0.7),
      size = 0.2,
      alpha = 0.3
    )  +
    
    
    labs(title = "D. Indirect effect sizes for selected mediators", x = "Mediator", y = "Mediated effect") +
    scale_fill_manual(
      values = c(
        "step1" = "purple",
        "step2" = "cyan",
        "ACME" = "black"
      ),
      name = "Ind. Effect :",
      labels = c(
        "step1" = "Effect of X on M", # a from "M ~ X"
        "step2" = "Effect of M on Y", # b from "Y ~ X + M"
        "ACME" = "ACME" # axb
      )
    ) + 
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top" )
  
  if(plot_type == "all_plot"){
  plot_final = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
  } else if(plot_type == "plot_ACME"){
    plot_final = p_ACME
  } else if(plot_type == "plot_Prop_Med"){
    plot_final = p_PM
  } else if(plot_type == "plot_overall_effects"){
    plot_final = p_effects
  } else if(plot_type == "plot_effect_size"){
    plot_final = p_es
  }
  return(plot_final)
}





##' Summary plot for univariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @param plot_type  "all_plot" by default generate all proposed plots , elsewhere choose one individual plot among : "plot_ACME", "plot_Prop_Med", "plot_overall_effects", "plot_effect_size"
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' K = 5
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = simu_data$X_categorial,
##'   Y = simu_data$Y_continuous,
##'   M = simu_data$M,
##'   K = K
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(object = hdmax2_step1, 
##'                                        m = mediators_top10)
##' # Generate plot
##' hdmax2::plot_univariate_cat(hdmax2_step2,  plot_type= "all_plot")
##' 
##' @import ggplot2
##' @importFrom stats reshape

plot_univariate_cat <- function(object,  plot_type= "all_plot") {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }
 n_cat = length(unique(object$input$X_input))-1
 plot_final = list()
 
  # Plot the ACME of the model
  for(k in 1:n_cat){
    p_ACME <-
      ggplot2::ggplot(
        object$effects$univariate[[k]]$ACME,
        aes(
          object$effects$univariate[[k]]$ACME$est,
          object$effects$univariate[[k]]$ACME$feat,
          #stats::reorder(object$ACME[[1]][[k]]$feat, object$ACME[[1]][[k]]$est),
          color = est <= 0,
          shape = pval <= 0.05
        )
      ) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$effects$univariate[[k]]$ACME$CI_2.5, xmax = object$effects$univariate[[k]]$ACME$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = "A. ACME (Average Causal Mediation Effect)", y = "Mediators", x =
             "Est. effect [CI 2.5-97.5]") +
      #xlab("ACME (Average Causal Mediation Effect)") +
      #ylab("CpG") +
      theme(
        panel.border = element_blank(),
        panel.spacing = unit(0.01, "lines"),
        axis.ticks = element_blank()
      ) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    
    ## Plot the mediated proportion
    
    p_PM <-
      ggplot2::ggplot(object$effects$univariate[[k]]$PM,
                      aes(
                        object$effects$univariate[[k]]$PM$est,
                        object$effects$univariate[[k]]$ACME$feat,
                        #stats::reorder(object$PM[[1]][[k]]$feat, object$PM[[1]][[k]]$est),
                        color = est <= 0,
                        shape = pval <= 0.05
                      )) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$effects$univariate[[k]]$PM$CI_2.5, xmax = object$effects$univariate[[k]]$PM$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = "B. Proportion Mediated (%)", y = "Mediators", x = "Est. proportion [CI 2.5-97.5]") +
      # xlab("Proportion Mediated (%)") +
      #ylab("CpG") +
      theme(
        panel.border = element_blank(),
        panel.spacing = unit(0.01, "lines"),
        axis.ticks = element_blank()
      ) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    ## Plot the overall effects
    
    df_effect = data.frame(OIE = object$effects$univariate[[k]]$oie_med, # median of OIE
                           OIE_CI = object$effects$univariate[[k]]$oie_sd, # confidence interval computed by boostrap
                           ODE =  object$effects$univariate[[k]]$ode[1], # coefficient of direct effect linear regression
                           ODE_sd =  object$effects$univariate[[k]]$ode[[1]], # sd of direct effect linear regression
                           OTE =  object$effects$univariate[[k]]$ote[1], # coefficient of total effect linear regression
                           OTE_sd =  object$effects$univariate[[k]]$ote[2]) # sd of total effect linear regression
    df_effect_long <-
      reshape(
        df_effect,
        varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
        v.names = c("value", "sd_value"),
        timevar = "variable",
        times = c("OIE", "ODE", "OTE"),
        direction = "long"
      )

    p_effects <-
      ggplot2::ggplot(df_effect_long, aes(
        x = df_effect_long$variable,
        y = df_effect_long$value,
        group = 1
      )) +
      geom_line() +
      geom_point(size = 3) +
      geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) +
      geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
      labs(title = "C. Overall effect",
           x = NULL,
           y = "Effect size") +
      theme_minimal() +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
        panel.grid.minor = element_blank(),
      )
    
    
    ## Plot the effect size
    
    df = data.frame(
      mediator = object$effects$univariate[[k]]$xm$feat,
      step1 = object$effects$univariate[[k]]$xm$Estimate,
      step2 = object$effects$univariate[[k]]$my$Estimate,
      ACME = object$effects$univariate[[k]]$ACME$est
    )
    df = dplyr::arrange(df, dplyr::desc(df$ACME))
    #df$mediator <- factor(df$mediator, levels = df$mediator)
    
    df_long <- data.frame(
      mediator = rep(df$mediator, 3),
      variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
      value = c(df$step1, df$step2, df$ACME)
    )
    
    p_es = ggplot2::ggplot(df_long, aes(
      x = factor(mediator),
      y = value,
      fill = variable
    )) +
      geom_bar(
        data = subset(df_long, variable == "ACME"),
        stat = "identity",
        position = position_dodge(width = 0.7),
        linewidth = 1.5
      )  +
      geom_bar(
        data = subset(df_long, variable != "ACME"),
        stat = "identity",
        position = position_dodge(width = 0.7),
        linewidth = 0.2,
        alpha = 0.3
      )  +
      
      
      labs(title = "D. Indirect effect sizes for selected mediators", x = "Mediator", y = "Mediated effect") +
      scale_fill_manual(
        values = c(
          "step1" = "purple",
          "step2" = "cyan",
          "ACME" = "black"
        ),
        name = "Ind. Effect :",
        labels = c(
          "step1" = "Effect of X on M", # a from "M ~ X"
          "step2" = "Effect of M on Y", # b from "Y ~ X + M"
          "ACME" = "ACME" # axb
        )
      ) + 
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top" )
    
    #plot_final[[k]] = gridExtra::grid.arrange(p_ACME, p_PM,  p_es, ncol = 2) # p_effects,
    #plot_final[[k]] = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
   
    if(plot_type == "all_plot"){
      plot_final[[k]] = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
    } else if(plot_type == "plot_ACME"){
      plot_final[[k]] = p_ACME
    } else if(plot_type == "plot_Prop_Med"){
      plot_final[[k]] = p_PM
    } else if(plot_type == "plot_overall_effects"){
      plot_final[[k]] = p_effects
    } else if(plot_type == "plot_effect_size"){
      plot_final[[k]] = p_es
    }
    
  }
  return(plot_final)
}





##' Summary plot for multivariate exposure variables 
##' This function draw a summary plot of hdmax2
##'
##' @param object results from hdmax2 step 2
##' @param plot_type  "all_plot" by default generate all proposed plots , elsewhere choose one individual plot among : "plot_ACME", "plot_Prop_Med", "plot_overall_effects", "plot_effect_size"
##' @return
##' Summary plot for ACME, PM, OIE, effects interpretation
##' @export
##' @author Florence Pittion, Magali Richard
##' @examples
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' X_matrix = data.frame(X1 = simu_data$X_continuous, X2 = simu_data$X_continuous_2)
##' Y_matrix = simu_data$Y_continuous
##' M_matrix = simu_data$M
##' K = 5
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X = X_matrix,
##'   Y = Y_matrix,
##'   M = M_matrix,
##'   K = K
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(object = hdmax2_step1, 
##'                                        m = mediators_top10)
##' # Generate plot
##' hdmax2::plot_multivariate(hdmax2_step2,  plot_type= "all_plot")
##' 
##' @import ggplot2
##' @importFrom stats reshape
##' 
##' 

plot_multivariate <- function(object,  plot_type= "all_plot") {
  
  if (class(object) != "hdmax2_step2") {
    stop(
      "The object is not of class hdmax2_step2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect"
    )
  }
  
  var_names = colnames(object$input$X_input)
  plot_final = list()
  
  for(var_name in var_names){
    
    p_ACME <- ggplot2::ggplot(object$effects[[var_name]]$ACME, aes(object$effects[[var_name]]$ACME$est, stats::reorder(object$effects[[var_name]]$ACME$feat, object$effects[[var_name]]$ACME$est), color = est <= 0, shape = pval <= 0.05)) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$effects[[var_name]]$ACME$CI_2.5, xmax = object$effects[[var_name]]$ACME$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = paste0("A. ACME of ", var_name), y = "Mediators", x="Est. effect [CI 2.5-97.5]") +
      #xlab("ACME (Average Causal Mediation Effect)") +
      #ylab("CpG") +
      theme(panel.border = element_blank(),
            panel.spacing = unit(0.01, "lines"),
            axis.ticks = element_blank()) +
      scale_color_manual(values = c("darkred", "darkgreen"))
    
    
    ##Plot the mediated proportion
    
    p_PM <- ggplot2::ggplot(object$effects[[var_name]]$PM, aes(object$effects[[var_name]]$PM$est, stats::reorder(object$effects[[var_name]]$PM$feat, object$effects[[var_name]]$PM$est), color = est <= 0, shape = pval <= 0.05)) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = object$effects[[var_name]]$PM$CI_2.5, xmax = object$effects[[var_name]]$PM$CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
      labs(title = paste0("B. PM of ", var_name), y = "Mediators", x="Est. proportion [CI 2.5-97.5]") +
      # xlab("Proportion Mediated (%)") +
      #ylab("CpG") +
      theme(panel.border = element_blank(),
            panel.spacing = unit(0.01, "lines"),
            axis.ticks = element_blank()) +
      scale_color_manual(values = c("darkred", "darkgreen")) 
    
    ##Plot the overall effects
    
    df_effect = data.frame(OIE = object$effects[[var_name]]$oie_med, # median of OIE
                           OIE_CI = object$effects[[var_name]]$oie_sd, # confidence interval computed by boostrap
                           ODE =  object$effects[[var_name]]$ode[1], # coefficient of direct effect linear regression
                           ODE_sd =  object$effects[[var_name]]$ode[2], # sd of direct effect linear regression
                           OTE =  object$effects[[var_name]]$ote[1], # coefficient of total effect linear regression
                           OTE_sd =  object$effects[[var_name]]$ote[2]) # sd of total effect linear regression
    df_effect_long <-
      reshape(
        df_effect,
        varying = list(c("OIE", "ODE", "OTE"), c("OIE_CI", "ODE_sd", "OTE_sd")),
        v.names = c("value", "sd_value"),
        timevar = "variable",
        times = c("OIE", "ODE", "OTE"),
        direction = "long"
      )
    
    p_effects <- ggplot2::ggplot(df_effect_long, aes(x = df_effect_long$variable, y = df_effect_long$value, group = 1)) +
      geom_line() +
      geom_point(size = 3) +
      geom_errorbar(aes(ymin = value - sd_value, ymax = value + sd_value), width = 0.2) + 
      geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
      labs(title = paste0("C. Overall effect of ", var_name),
           x = NULL,
           y = "Effect size") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            #axis.title.y = element_blank(),
            panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
            panel.grid.minor = element_blank(),
            #plot.title = element_text(hjust = 0.5)
      )
    
    ##Plot the effect size
    
    df = data.frame( mediator = object$effects[[var_name]]$xm$feat,
                     step1 = object$effects[[var_name]]$xm$Estimate,
                     step2 = object$effects[[var_name]]$my$Estimate,
                     ACME = object$effects[[var_name]]$ACME$est)
    df = dplyr::arrange(df, dplyr::desc(df$ACME))
    df$mediator <- factor(df$mediator, levels = df$mediator)
    
    df_long <- data.frame(
      mediator = rep(df$mediator, 3),
      variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
      value = c(df$step1, df$step2, df$ACME)
    )
    
    p_es = ggplot2::ggplot(df_long, aes(x = factor(mediator), y = value, fill = variable)) +
      geom_bar(data = subset(df_long, variable == "ACME"), stat="identity", position=position_dodge(width = 0.7), linewidth = 1.5)  +
      geom_bar(data = subset(df_long, variable != "ACME"), stat="identity", position=position_dodge(width = 0.7), linewidth = 0.2,  alpha = 0.3)  +
      
      #geom_text(aes(label = round(value, 2)), position=position_dodge(width = 0.7), vjust = -0.5) +  # Ajouter les étiquettes de taille d'effet
      labs(title = paste0("D. Effect sizes of ", var_name), x = "Mediator", y = "Mediated effect") +
      scale_fill_manual(values = c("step1" = "purple", "step2" = "cyan", "ACME" = "black"),
                        name = "Effects",
                        labels = c(
                          "step1" = "Effect of X on M", # a from "M ~ X"
                          "step2" = "Effect of M on Y", # b from "Y ~ X + M"
                          "ACME" = "ACME" # axb
                        )) +  # Personnalisation de la légende
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))# +
    # guides(fill = guide_legend(override.aes = list(size = c(0.5, 0.5, NA))))  # Ne pas afficher l'épaisseur pour ACME dans la légende
    
    
    #patchwork::combined_plot <- (p_ACME + p_PM) / (p_effects + p_es)
    
    #plot_final = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
    
    if(plot_type == "all_plot"){
      plot_final[[var_name]] = gridExtra::grid.arrange(p_ACME, p_PM, p_effects, p_es, ncol = 2)
    } else if(plot_type == "plot_ACME"){
      plot_final[[var_name]]= p_ACME
    } else if(plot_type == "plot_Prop_Med"){
      plot_final[[var_name]] = p_PM
    } else if(plot_type == "plot_overall_effects"){
      plot_final[[var_name]] = p_effects
    } else if(plot_type == "plot_effect_size"){
      plot_final[[var_name]] = p_es
    }
  }
  return(plot_final)
}

