##' Summary plot for ACME
##'
##' This function draw a summary plot of ACME (average causal mediation effect)
##'
##' @param res_step2 the table of ACME from the wrap_mediation() function
##' @param N_med number of selected mediators
##' @return
##' Summary plot for ACME
##'
##'
##' @export
##' @author Basile Jumentier
##' @examples
##'
##' # see wrap_mediation example
##'
##' @import ggplot2
##'


plot_hdmax2 <- function(res_step2, N_med = 10) {
 
  
  
  if (class(object)!="hdmax2"){
  stop("The object is not of class hdmax2. This function only plots hdmax2 objects generated by hdmax2::estimate_effect")
    }
  
	#Plot the ACME of the model
	
	p_ACME <- ggplot2::ggplot(res_step2$ACME, aes(est, stats::reorder(feat, est), color = est <= 0, shape = pval <= 0.05)) +
	    geom_vline(xintercept = 0, linetype = "dashed") +
	    geom_errorbarh(aes(xmin = CI_2.5, xmax = CI_97.5)) +
	    geom_point(size = 2.8) +
	    theme_bw() +
	    labs(title = "A. ACME (Average Causal Mediation Effect)", y = "Mediators", x="Est. effect [CI 2.5-97.5]") +
	    #xlab("ACME (Average Causal Mediation Effect)") +
	    #ylab("CpG") +
	    theme(panel.border = element_blank(),
	          panel.spacing = unit(0.01, "lines"),
	          axis.ticks = element_blank()) +
	    scale_color_manual(values = c("darkred", "darkgreen"))
		
		
  ##Plot the mediated proportion
  
  p_PM <- ggplot2::ggplot(res_step2$PM, aes(est, stats::reorder(feat, est), color = est <= 0, shape = pval <= 0.05)) +
      geom_vline(xintercept = 0, linetype = "dashed") +
      geom_errorbarh(aes(xmin = CI_2.5, xmax = CI_97.5)) +
      geom_point(size = 2.8) +
      theme_bw() +
       labs(title = "B. Proportion Mediated (%)", y = "Mediators", x="Est. proportion [CI 2.5-97.5]") +
     # xlab("Proportion Mediated (%)") +
      #ylab("CpG") +
      theme(panel.border = element_blank(),
            panel.spacing = unit(0.01, "lines"),
            axis.ticks = element_blank()) +
      scale_color_manual(values = c("darkred", "darkgreen")) 
	  
  ##Plot the overall effects
  
  df_effect = data.frame(OIE = res_step2$oie_med,
                         ODE =  res_step2$ode[2],
                         OTE =  res_step2$ote[2] )
  df_effect_long <- reshape(df_effect, direction = "long", varying = 1:3, v.names = "value", timevar = "variable", times = c("OIE", "ODE", "OTE"))

  p_effects <- ggplot2::ggplot(df_effect_long, aes(x = variable, y = value, group = 1)) +
    geom_line() +
    geom_point(size = 3) +
    geom_label(aes(label = round(value, 2)), label.padding = unit(0.1, "lines")) +
    labs(title = "C. Overall effect",
         x = NULL,
         y = "Effect size") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          #axis.title.y = element_blank(),
          panel.grid.major = element_line(colour = "gray", linetype = "dotted"),
          panel.grid.minor = element_blank(),
          #plot.title = element_text(hjust = 0.5)
          )

  ##Plot the effect size
  
  df = data.frame( mediator = res_step2$xm$feat,
                   step1 = res_step2$xm$Estimate,
                         step2 = res_step2$my$Estimate,
                   ACME = res_step2$ACME$est)
  df = dplyr::arrange(df, desc(ACME))
  df$mediator <- factor(df$mediator, levels = df$mediator)

  df_long <- data.frame(
    mediator = rep(df$mediator, 3),
    variable = rep(c("step1", "step2", "ACME"), each = nrow(df)),
    value = c(df$step1, df$step2, df$ACME)
  )
  
  p_es = ggplot2::ggplot(df_long, aes(x = factor(mediator), y = value, fill = variable)) +
        geom_bar(data = subset(df_long, variable == "ACME"), stat="identity", position=position_dodge(width = 0.7), size = 1.5)  +
      geom_bar(data = subset(df_long, variable != "ACME"), stat="identity", position=position_dodge(width = 0.7), size = 0.2,  alpha = 0.3)  +
 
      #geom_text(aes(label = round(value, 2)), position=position_dodge(width = 0.7), vjust = -0.5) +  # Ajouter les étiquettes de taille d'effet
      labs(title = "D. Effect sizes", x = "Mediator", y = "Mediated effect") +
      scale_fill_manual(values = c("step1" = "purple", "step2" = "cyan", "ACME" = "black"), 
                        name = "Effects", 
                        labels = c("step1" = "M ~ X", "step2" = "Y ~ X + M", "ACME" = "ACME")) +  # Personnalisation de la légende
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))# +
     # guides(fill = guide_legend(override.aes = list(size = c(0.5, 0.5, NA))))  # Ne pas afficher l'épaisseur pour ACME dans la légende
    

	 #patchwork::combined_plot <- (p_ACME + p_PM) / (p_effects + p_es) 
	 
	 plot_final = gridExtra::grid.arrange(p_ACME + p_PM, p_effects + p_es, ncol = 2)
	 
	 return(plot_final)

}  