##' Estimate effects for a set of mediation markers
##' V2 this version allow to integrate covariates in mediation function 
##'
##' Estimate various quantities for causal mediation analysis for a set of
##' markers, including average causal mediation effects
##' (indirect effect), average direct effects, proportions mediated,
##' and total effect.
##'
##' @param object results from hdmax2 step 2
##' @param m a response variable matrix with n rows and p columns corresponding to mediators selected at step1.
##' Response variables must be encoded as numeric. No NAs allowed.
##' @param sims number of Monte Carlo draws for nonparametric bootstrap or quasi-Bayesian approximation.
##' 10000 is recommended.
##' @param boots number of bootstrap
##' @param is.categorial A a logical variable, if true, one mode of the categorical variable will be arbitrarily removed to avoid collinearity. Caution: if X is a mixture of categorical variables and other variables, you must remove a mode from the categorical variable beforehand, and indicate this parameter as FALSE.
##' @return hdmax2_step2 object
##' 
##'  - ACME, estimation of the average causal mediation effect (the indirect effect)
##'  - ADE, estimation average direct effect
##'  - PM, estimation of the proportion mediated
##'  - TE, estimation of the total effect
##'  
##' Regressions:
##'  - xm, regression X on M
##'  - my, regression M on Y
##' 
##' 
##' Overall effect
##'  - oie, overall indirect effect
##'  - oie_med , oie median
##'  - oie_sd , oie standard deviation
##'  - ote, overall total effect
##'  - ode, overall direct effect
##'  
##' @details
##'
##' We use the mediate function of the mediation package on the set of markers having Q-value lower
##' than the FDR threshold. It estimates their indirect effects and 
##' tests their significance.
##'
##' @export
##' @author Florence Pittion
##' @examples 
##' # Load example dataset
##' simu_data = hdmax2::simu_data
##' # Run {hdmax2} step 1
##' hdmax2_step1 = hdmax2::run_AS(
##'   X_matrix = as.matrix(simu_data$X_continuous) ,
##'   Y_matrix =  as.matrix(simu_data$Y_continuous),
##'   M_matrix =  as.matrix(simu_data$M)
##' )
##' # Select mediators
##' mediators_subset = names(sort(hdmax2_step1$max2_pvalues)[1:10])
##' mediators_top10 = simu_data$M[, mediators_subset]
##' # Run {hdmax2} step 2
##' hdmax2_step2 = hdmax2::estimate_effect(
##'    object = hdmax2_step1, 
##'    m = mediators_top10)

estimate_effect <- function(object , m, boots = 100, sims = 3, is.categorial = FALSE) {
  
  if (class(object)!="hdmax2_step1"){
    stop("The object is not of class hdmax2_step1. This function only compute hdmax2 objects generated by hdmax2::run_AS")
  }
  
  
  Y = object$input$Y_matrix
  X_type = object$input$X_type
  Y_type = object$input$Y_type
  
  M = m
  if (is.null(colnames(M))) {
    colnames(M) <- 1:ncol(M)
  }
  
  ################################################
  ### Estimate effects for univariate exposome ###
  ################################################
  
  if(object$input$X_type == "univariate"){
   
    print("Estimating indirect effect for univariate exposome.")   
    
    X = as.matrix(object$input$X_matrix)
    
    if (is.null(object$input$covar)) {
      covars = data.frame(latent_factors = object$modele_1$U)
    } else  {
      covars = data.frame(obs_covar = object$input$covar, latent_factors = object$modele_1$U)
    }
    
    
    
    
    ### Compute ACME, ADE, PM and TE from package mediation
    
    # from package mediation
    ACME <- matrix(ncol = 4, nrow = ncol(M))
    ADE <- matrix(ncol = 4, nrow = ncol(M))
    PM <- matrix(ncol = 4, nrow = ncol(M))
    TE <- matrix(ncol = 4, nrow = ncol(M))
    
    # from linear models
    xm <- matrix(ncol = 4, nrow = ncol(M))
    my <- matrix(ncol = 4, nrow = ncol(M))
    
    ###############################
    # covars are considered in mediate function but not in input regression modele
    ###############################
    
    for (i in 1:ncol(M)) {
      
      if (is.null(object$input$covar)) {
        dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U)
      } else  {
        dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar)
      }
      
      if (is.null(object$input$covar)) {
        dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, Y = Y)
      } else  {
        dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, Y = Y)
      }
      
      
      # dat.x <- data.frame(X = X, Mi = M[, i], covars = covars)
      # dat.y <- data.frame(X = X, Mi = M[, i], Y = Y, covars = covars)
      
      # ici cas de deux reg lineaires pour les deux associations
      # TODO refaire pour les autres regressions
      
      
      mod1 <- stats::lm(Mi ~ X + ., data = dat.x)
      
      if(Y_type=="continuous"){
		  print(paste0("Generate regression 2 for continuous outcome and mediator ", i))   
        mod2 <- stats::lm(Y ~ X + Mi + ., data = dat.y)
      }
      
      if(Y_type=="binary"){
		   print(paste0("Generate regression 2 for binary outcome and mediator ", i))
        mod2 <- stats::glm(Y ~ X + Mi + ., family = "binomial", data = dat.y)
      }
      
      # if(mod2_type=="surv_Cox"){
      # mod2 = survival::survreg(Y ~ X + Mi , dist='exponential', data = dat.y)
      # }
      
      
      # for linear models
      xm[i, ] <- summary(mod1)$coeff[2, ] # effect of X
      #if(Y_type=="binary"){
      my[i, ] <- summary(mod2)$coeff[3, ] # effect of M
      #}
      
      
      med <- mediation::mediate(mod1, mod2, sims = sims, treat = "X", mediator = "Mi", covariates = dat.x[,3:dim(dat.x)[2]])
      
      ACME[i, ] <- c(med$d0, med$d0.ci[1], med$d0.ci[2], med$d0.p)
      ADE[i, ] <- c(med$z0, med$z0.ci[1], med$z0.ci[2], med$z0.p)
      PM[i, ] <- c(med$n0, med$n0.ci[1], med$n0.ci[2], med$n0.p)
      TE[i, ] <- c(med$tau.coef, med$tau.ci[1], med$tau.ci[2], med$tau.p)
    }
    
    ACME <- as.data.frame(ACME)
    ADE <- as.data.frame(ADE)
    PM <- as.data.frame(PM)
    TE <- as.data.frame(TE)
    xm <- as.data.frame(xm)
    my <- as.data.frame(my)
    
    colnames(ACME) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(ADE) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(PM) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(TE) <- c("est", "CI_2.5", "CI_97.5", "pval")
    colnames(xm) <- c("Estimate", "Std.Error", "t.Value", "pValue")
    colnames(my) <- c("Estimate", "Std.Error", "t.Value", "pValue")
    
    ACME$feat <- colnames(M)
    ADE$feat <- colnames(M)
    PM$feat <- colnames(M)
    TE$feat <- colnames(M)
    xm$feat <- colnames(M)
    my$feat <- colnames(M)
    
    ### Compute OIE by bootstrap
    
    # bootstrap
    acme_sum <- matrix(nrow = 1, ncol = boots)
    covars = as.matrix(covars)
    
    for (i in 1:ncol(acme_sum)) {
      samp <- sample(length(X), replace = T)
      
      
      # effet A X -> M
      mod1 <- lm(m[samp, ] ~ X[samp] + covars[samp, ])
      A <- t(sapply(summary(mod1), function(x) x$coeff[2, ]))
      A <- data.frame(feat = rownames(A), A)
      # A <- separate(A, CpG, c("0", "CpG"), " ")[, -1]
      
      
      # effet B m -> Y
      if(Y_type=="binary"){
        dat.1 <- data.frame(X, m, covars = covars)
        mod2 <- glm(Y[samp] ~ .,family = "binomial" , data = dat.1[samp, ])
        B <- as.data.frame(summary(mod2)$coeff[3:(ncol(m) + 2), ])
      } 
      
      if(Y_type=="continuous"){
        dat.1 <- data.frame(X, m, covars = covars)
        mod2 <- lm(Y[samp] ~ ., data = dat.1[samp, ])
        B <- as.data.frame(summary(mod2)$coeff[3:(ncol(m) + 2), ])
        #B <- as.data.frame(summary(mod2)$coeff[3:10, ])
      }
      
      
      colnames(B) <- c("B", "B_sd", "B_tv", "B_pv")
      colnames(A)[2:5] <- c("A", "A_sd", "A_tv", "A_pv")
      
      ab <- cbind(A, B)
      rownames(ab) <- NULL
      
      # effet A*B
      ab$AB <- ab$A * ab$B
      
      acme_sum[i] <- sum(ab$AB)
    }
    
    ### Compute ODE and OTE for the given model
    
    if(Y_type == "continuous") {
      print("Computing ODE and OTE for continuous outcome.")
      mod_total_effect = lm(Y ~ X + covars)
      mod_direct_effect = lm(Y ~ X + mediators_top10 + covars)
      
    }
    
    if(Y_type == "binary") {
      print("Computing ODE and OTE for binary outcome.")
      mod_total_effect = glm(Y ~ X + covars, family = "binomial")
      mod_direct_effect = glm(Y ~ X + mediators_top10 + covars, family = "binomial")
    }
    
    ote = summary(mod_total_effect)$coefficients[2,]
    ode = summary(mod_direct_effect)$coefficients[2,]
    
    obj = list(ACME = ACME,
               ADE = ADE,
               PM = PM,
               TE = TE,
               xm = xm,
               my = my,
               oie = as.vector(acme_sum),
               oie_med = median(as.vector(acme_sum)),
               oie_sd = sd(as.vector(acme_sum)),
               ote = ote,
               ode = ode,
               input = object$input,
               M = M
    )
  }
  
  ################################################
  ### Estimate effects for multivariate exposome ###
  ################################################
  
  if(object$input$X_type=="multivariate"){
    #if (object$input$multivariate) {
    
    print("Estimating indirect effect for multivariate exposome.")
    
    n = dim(object$input$X_matrix)[2]

    var_names = colnames(object$input$X_matrix)
    
    ACMEs = list() 
    ADEs = list()
    PMs = list()
    TEs = list()
    xms = list()
    mys = list()
    oies = list()
    oies_med = list()
    oies_sd = list()
    otes = list()
    odes = list()
    
    # Run models for each explanatory variable (by integrating other variables as covariates of the model)
    
    for(var_name in (var_names)){
      M =m
      #if (is.null(colnames(M))) {
      #  colnames(M) <- 1:ncol(M)
      #}
      
      print(paste0("A model is run to estimate indirect effect of the following explanatory variable: ", var_name))
      
      X = as.matrix(object$input$X_matrix[,var_name])
      X_otherVars = as.data.frame(object$input$X_matrix[,-which(var_name == colnames(object$input$X_matrix))])
      
      if( is.categorial == TRUE){
        print("One mode of the categorical variable is arbitrarily removed to avoid collinearity.")
        X_otherVars = X_otherVars[,-(n-2)]
      }
      
      # Associate the other explanatory variables with known covariates 
      if (is.null(object$input$covar)) {
        covars = data.frame(latent_factors = object$modele_1$U, X_otherVars = X_otherVars)
      } else  {
        covars = data.frame(obs_covar = object$input$covar, latent_factors = object$modele_1$U, X_otherVars = X_otherVars)
      }
      
      # from package mediation
      ACME <- matrix(ncol = 4, nrow = ncol(M))
      ADE <- matrix(ncol = 4, nrow = ncol(M))
      PM <- matrix(ncol = 4, nrow = ncol(M))
      TE <- matrix(ncol = 4, nrow = ncol(M))
      
      # from linear models
      xm <- matrix(ncol = 4, nrow = ncol(M))
      my <- matrix(ncol = 4, nrow = ncol(M))
      
      for (i in 1:ncol(M)) {
        
        if (is.null(object$input$covar)) {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U,  X_otherVars = X_otherVars)
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U,  X_otherVars = X_otherVars, Y = Y)
        } else  {
          dat.x <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, X_otherVars =X_otherVars)
          dat.y <- data.frame(X = X, Mi = M[, i], latent_factors = object$modele_1$U, obs_covar = object$input$covar, X_otherVars =X_otherVars, Y = Y)
        }
        
        mod1 <- stats::lm(Mi ~ X + ., data = dat.x)
        
        if(Y_type=="continuous"){
          mod2 <- stats::lm(Y ~ X + Mi + ., data = dat.y)
        }
        
        if(Y_type=="binary"){
          mod2 <- stats::glm(Y ~ X + Mi + ., data = dat.y)
        }
        
        # for linear models
        xm[i, ] <- summary(mod1)$coeff[2, ] # effect of X
        #if(Y_type=="binary"){
        my[i, ] <- summary(mod2)$coeff[3, ] # effect of M
        #}
        
        
        med <- mediation::mediate(mod1, mod2, sims = sims, treat = "X", mediator = "Mi", covariates = dat.x[,3:dim(dat.x)[2]])
        
        ACME[i, ] <- c(med$d0, med$d0.ci[1], med$d0.ci[2], med$d0.p)
        ADE[i, ] <- c(med$z0, med$z0.ci[1], med$z0.ci[2], med$z0.p)
        PM[i, ] <- c(med$n0, med$n0.ci[1], med$n0.ci[2], med$n0.p)
        TE[i, ] <- c(med$tau.coef, med$tau.ci[1], med$tau.ci[2], med$tau.p)
      }
      
      ACME <- as.data.frame(ACME)
      ADE <- as.data.frame(ADE)
      PM <- as.data.frame(PM)
      TE <- as.data.frame(TE)
      xm <- as.data.frame(xm)
      my <- as.data.frame(my)
      
      colnames(ACME) <- c("est", "CI_2.5", "CI_97.5", "pval")
      colnames(ADE) <- c("est", "CI_2.5", "CI_97.5", "pval")
      colnames(PM) <- c("est", "CI_2.5", "CI_97.5", "pval")
      colnames(TE) <- c("est", "CI_2.5", "CI_97.5", "pval")
      colnames(xm) <- c("Estimate", "Std.Error", "t.Value", "pValue")
      colnames(my) <- c("Estimate", "Std.Error", "t.Value", "pValue")
      
      ACME$feat <- colnames(M)
      ADE$feat <- colnames(M)
      PM$feat <- colnames(M)
      TE$feat <- colnames(M)
      xm$feat <- colnames(M)
      my$feat <- colnames(M)
      
      ACMEs[[var_name]] = ACME 
      ADEs[[var_name]] = ADE
      PMs[[var_name]] = PM
      TEs[[var_name]] = TE
      xms[[var_name]] = xm
      mys[[var_name]] = my
      
      ### Compute OIE by bootstrap
      
      # bootstrap
      acme_sum <- matrix(nrow = 1, ncol = boots)
      covars = as.matrix(covars)
      
      for (i in 1:ncol(acme_sum)) {
        samp <- sample(length(X), replace = T)
        
        # effet A X -> M
        mod1 <- lm(M[samp, ] ~ X[samp] + covars[samp, ])
        A <- t(sapply(summary(mod1), function(x) x$coeff[2, ]))
        A <- data.frame(feat = rownames(A), A)
        # A <- separate(A, CpG, c("0", "CpG"), " ")[, -1]
        
        
        # effet B m -> Y
        if(Y_type=="binary"){
          dat.1 <- data.frame(X, M, covars = covars)
          mod2 <- glm(Y[samp] ~ ., family = "binomial", data = dat.1[samp, ])
          B <- as.data.frame(summary(mod2)$coeff[3:(ncol(M) + 2), ])
        } 
        
        if(Y_type=="continuous"){
          dat.1 <- data.frame(X, M, covars = covars)
          mod2 <- lm(Y[samp] ~ ., data = dat.1[samp, ])
          B <- as.data.frame(summary(mod2)$coeff[3:(ncol(M) + 2), ])
          #B <- as.data.frame(summary(mod2)$coeff[3:10, ])
        }
        
        
        colnames(B) <- c("B", "B_sd", "B_tv", "B_pv")
        colnames(A)[2:5] <- c("A", "A_sd", "A_tv", "A_pv")
        
        ab <- cbind(A, B)
        rownames(ab) <- NULL
        
        # effet A*B
        ab$AB <- ab$A * ab$B
        
        acme_sum[i] <- sum(ab$AB)
      }
      
      
      ### Compute ODE and OTE for the given model
      
      if(Y_type == "continuous") {
        print("Computing ODE and OTE for continuous outcome.")
        mod_total_effect = lm(Y ~ X + covars)
        mod_direct_effect = lm(Y ~ X + mediators_top10 + covars)
        
      }
      
      if(Y_type == "binary") {
        print("Computing ODE and OTE for binary outcome.")
        mod_total_effect = glm(Y ~ X + covars, family = "binomial")
        mod_direct_effect = glm(Y ~ X + mediators_top10 + covars, family = "binomial")
      }
      
      ote = summary(mod_total_effect)$coefficients[2,]
      ode = summary(mod_direct_effect)$coefficients[2,]
    
    
    oie = as.vector(acme_sum)
    oie_med = median(as.vector(acme_sum))
    oie_sd = sd(as.vector(acme_sum))
    ote = ote
    ode = ode
    
    oies[[var_name]]= oie
    oies_med[[var_name]] = oie_med
    oies_sd[[var_name]] = oie_sd
    otes[[var_name]] = ote
    odes[[var_name]] = ode
    
  }

  
  obj = list(ACME = ACMEs,
             ADE = ADEs,
             PM = PMs,
             TE = TEs,
             xm = xms,
             my = mys,
             oie = oies,
             oie_med = oies_med,
             oie_sd = oies_sd,
             ote = otes,
             ode = odes,
             input = object$input,
             M = M
  )
  
  }
  class(obj) = "hdmax2_step2"
  
  return(obj)
  
}
  